version: '3'

services:
  weaviate-obsidian:
    container_name: weaviate-obsidian
    depends_on:
      - t2v-transformers-obsidian
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate
    ports:
    - 3636:8080
    volumes:
      - ./weaviate-data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers-obsidian:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'


  t2v-transformers-obsidian:
    container_name: t2v-transformers-obsidian
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    restart: unless-stopped
    environment:
      ENABLE_CUDA: '0'


